DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255), UUID VARCHAR(100),REGISTRATION_DATE datetime);

DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255), AGE INT, PREVIOUS_VISIT_DATE datetime);